version: '3.1'
services:
  app:
    container_name: test-task
    image: test
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MYAPP_JDBC_URL=jdbc:postgresql://db:5432/petdb
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=petdb
      - POSTGRES_HOST_AUTH_METHOD=trust
